# Kakao OAuth
kakao:
  rest-api-key: 8895a2ddc4885c7ded353d9a4b5dc7fa
  client-secret: 5hi82QnpRiYWdNlyOskQ1w4TZW9Glhr4
  redirect-uri: http://localhost:4000/auth/kakao/callback
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me